product: ubuntu2004
full_name: "Ubuntu 20.04"
type: platform

benchmark_root: "../../linux_os/guide"

profiles_root: "./profiles"

pkg_manager: "apt_get"
pkg_manager_config_file: "/etc/apt/apt.conf"

init_system: "systemd"
oval_feed_url: "https://people.canonical.com/~ubuntu-security/oval/com.ubuntu.focal.cve.oval.xml"

grub2_boot_path: "/boot/grub"
grub2_uefi_boot_path: "/boot/grub"

aide_bin_path: "/usr/bin/aide.wrapper"
aide_conf_path: "/etc/aide/aide.conf"
aide_default_path: "/etc/default/aide"
chrony_conf_path: "/etc/chrony/chrony.conf"

aide_conf_path: "/etc/aide/aide.conf"

cpes_root: "../../shared/applicability"
cpes:
  - ubuntu2004:
      name: "cpe:/o:canonical:ubuntu_linux:20.04::~~lts~~~"
      title: "Canoncal Ubuntu Linux 20.04 LTS (Long-Term Support)"
      check_id: installed_OS_is_ubuntu2004

platform_package_overrides:
  audit: auditd
  avahi: avahi-daemon
  gdm: gdm3
  grub2: grub2-common
  net-snmp: snmp
  nss-pam-ldapd: libpam-ldap
  pam: libpam-runtime
  pam_pwquality: libpam-pwquality
  shadow: login
  sssd: sssd-common
