# platform = multi_platform_all
# reboot = false
# strategy = restrict
# complexity = low
# disruption = low

- name: Ensure interactive local users are the owners of their respective initialization files
  ansible.builtin.command:
    cmd: |
      awk -F':' '{ if ($3 >= {{{ uid_min }}} && $3 != {{{ nobody_uid }}}) system("find "$6" -maxdepth 1 -name \.[^.]?* -exec chown -f "$3" {} \;") }' /etc/passwd
